version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: saints-sqlserver
    environment:
      SA_PASSWORD: "Password@1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  sql_data:
